<?php
	include_once('functions/functions-options.php');
	include_once('functions/functions-cpt.php');
	include_once('functions/functions-menus.php');
	include_once('functions/functions-thumbnails.php');
	include_once('functions/functions-comments.php');
	include_once('functions/functions-yoast.php');
	include_once('functions/functions-cleanup.php');
	include_once('functions/functions-scripts.php');
	include_once('functions/functions-admin.php');
	include_once('functions/functions-acf.php');
	include_once('functions/functions-walkers.php');
	include_once('functions/functions-ajax.php');